# Site settings
title: "Brady Gerndt"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brady J Gerndt"
resume_title:                   "Software Engineer"
resume_contact_email:           "brady.gerndt@gmail.com"
resume_header_contact_info:     "brady.gerndt@gmail.com"
resume_header_intro: 
  <p>
    IT professional with 6 years of experience implementing technology in the automotive industry. I've spent time as a systems analyst, innovation architect, infrastructure analyst and front-end developer for an ITSM platform. I employ creativity, adaptability and professionalism to solve problems with the technology at hand. My greatest career revelation is that culture drives success.
  </p>
resume_experience_details: 
  #<p>I'm currently part of an IT leadership development program at Harley-Davidson.</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_certification: true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bradygerndt"
  #resume_twitter_url:        
  #resume_dribbble_url:          
  # resume_facebook_url:         "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/bradygerndt"
  # resume_instagram_url:        "insert your Instagram URL here"
  #resume_website_url:           "
  resume_terminal_url:          "https://www.bradygerndt.info/bradyterm/"
resume_print_social_links:      false

# Design settings
resume_theme:                   

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

#Extra config stuff down here. Plugins... includes...

#Don't need this on github's server
#include: [".well-known"]

plugins:
  - jekyll-seo-tag

description: "Brady Gerndt, Milwaukee based software engineer"
author: Brady Gerndt
lang: en_US

google_analytics:
  <!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-105438922-1"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-105438922-1');</script>



